# **** Numpy Array Introduction ****#

##  Array Creation ##

In [176]:
import numpy as np

arr_Valid = np.array([[3,5,2],[7,4,1],[7,6,5]])
print("Valid array when data equaly provided")
print(arr_Valid)
print("---------------------------------")

print("Invalid array when data equaly provided, its become array of list")
arr_InValid = np.array([[3,5,2],[7,4,1,4],[7,6]])
print(arr_InValid)
print("---------------------------------")

print("Array with zeros")
arr_Valid = np.zeros((2,5))
print(arr_Valid)
print("---------------------------------")

print("Array with ones")
arr_Valid = np.ones((4,2))
print(arr_Valid)
print("---------------------------------")

print("Array with list/touple")
lst = [(6,7,8),[1,2,3]]
arr_Valid = np.asarray(lst)
print(lst)
print(arr_Valid)
print(arr_Valid*2)
print("---------------------------------")


print("Array with linespace")
arr_Valid = np.linspace(0,100,5,True)
print(arr_Valid)

print("Matrix with linespace ")
arr_Valid = np.linspace((0,0),(100,10),5)
print(arr_Valid)
print("---------------------------------")

print("Array with arrange")
arr_Valid = np.arange(5)
print(arr_Valid)
arr_Valid = np.arange(0,30,3)
print(arr_Valid)

Valid array when data equaly provided
[[3 5 2]
 [7 4 1]
 [7 6 5]]
---------------------------------
Invalid array when data equaly provided, its become array of list
[list([3, 5, 2]) list([7, 4, 1, 4]) list([7, 6])]
---------------------------------
Array with zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
---------------------------------
Array with ones
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------------------------
Array with list/touple
[(6, 7, 8), [1, 2, 3]]
[[6 7 8]
 [1 2 3]]
[[12 14 16]
 [ 2  4  6]]
---------------------------------
Array with linespace
[  0.  25.  50.  75. 100.]
Matrix with linespace 
[[  0.    0. ]
 [ 25.    2.5]
 [ 50.    5. ]
 [ 75.    7.5]
 [100.   10. ]]
---------------------------------
Array with arrange
[0 1 2 3 4]
[ 0  3  6  9 12 15 18 21 24 27]


## Data Type ##

In [47]:

arr_Valid = np.array([[3,5,2],[7,4,1],[7,6,'a']])
print("Array without datatype : ")
print(arr_Valid)
("---------------------------------")
dt = np.dtype('i1') # np.dtype('int8')
print(dt)
print("---------------------------------")
print("Array with datatype : ")
#arr_InValid = np.array([[3,5,2],[7,4,1],[7,6,'a']],dtype=dt)
#print(arr_InValid)
arr_Valid = np.array([[3,5,2],[7,4,1],[7,6,4]],dtype=dt)
print(arr_Valid)

print("---------------------------------")
print("Array with multi datatype : ")
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
arr_student = np.array([('John', 21, 50),('Allen', 18, 75)], dtype = student) 
print(arr_student)

Array without datatype : 
[['3' '5' '2']
 ['7' '4' '1']
 ['7' '6' 'a']]
int8
---------------------------------
Array with datatype : 
[[3 5 2]
 [7 4 1]
 [7 6 4]]
---------------------------------
Array with multi datatype : 
[(b'John', 21, 50.) (b'Allen', 18, 75.)]


#### In-built Datatype ####
<ul>
<li> 'b' − boolean </li> 
<li> 'i' − (signed) integer </li> 
<li> 'u' − unsigned integer </li> 
<li> 'f' − floating-point </li> 
<li> 'c' − complex-floating point </li> 
<li> 'm' − timedelta </li> 
<li> 'M' − datetime </li> 
<li> 'O' − (Python) objects </li> 
<li> 'S', 'a' − (byte-)string </li> 
<li> 'U' − Unicode </li> 
<li> 'V' − raw data (void) </li> 
</ul>


## Indexing & Slicing ##

In [160]:
print("1-D Array Slicing")
arr_Valid = np.arange(10)
print(arr_Valid)
print(arr_Valid[3:7])
print(arr_Valid[3:7:2])
print("---------------------------------")

print("2-D Array")
arr_Valid = np.array([[1,2,3],[10,20,20],[100,200,300]])
print(arr_Valid)
print("---------------------------------")

print("2-D Array Slicing for Row")
print(arr_Valid[0:2])
print("---------------------------------")

print("2-D Array Slicing fro Column")
print(arr_Valid[...,0:2])
print("---------------------------------")

print("1-D Array Indexing")
arr_Valid = np.arange(10)
print(arr_Valid)
print(arr_Valid[2])
print("---------------------------------")

print("2-D Array Indexing")
arr_Valid = np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400],[111,222,333,444]]) 
print(arr_Valid)
print(arr_Valid[2,1])

1-D Array Slicing
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[3 5]
---------------------------------
2-D Array
[[  1   2   3]
 [ 10  20  20]
 [100 200 300]]
---------------------------------
2-D Array Slicing for Row
[[ 1  2  3]
 [10 20 20]]
---------------------------------
2-D Array Slicing fro Column
[[  1   2]
 [ 10  20]
 [100 200]]
---------------------------------
1-D Array Indexing
[0 1 2 3 4 5 6 7 8 9]
2
---------------------------------
2-D Array Indexing
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]
 [111 222 333 444]]
200


## Broadcasting ##

In [173]:
print("2-D Array")
arr_Valid = np.array([[1,2,3],[10,20,30],[100,200,200]])
print(arr_Valid)
print("---------------------------------")

print("Multiply with value")
print(arr_Valid * 2)
print("---------------------------------")

print("Multiply/Addition with 1-D Array")
arr_second = np.array([1,2,3])
print(arr_Valid * arr_second)
print(arr_Valid + arr_second)
print("---------------------------------")


2-D Array
[[  1   2   3]
 [ 10  20  30]
 [100 200 200]]
---------------------------------
Multiply with value
[[  2   4   6]
 [ 20  40  60]
 [200 400 400]]
---------------------------------
Multiply/Addition with 1-D Array
[[  1   4   9]
 [ 10  40  90]
 [100 400 600]]
[[  2   4   6]
 [ 11  22  33]
 [101 202 203]]
---------------------------------


## Iterating ##

In [200]:
print("Array Iterating")
arr_Valid = np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(arr_Valid):
   print(x),
print("---------------------------------")

print("Array Reshaping")
arr_reshape1 = arr_Valid.reshape(1,9)
print(arr_reshape1)
print("---------------------------------")


print("Transpose")
arr_Valid = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_Valid)
print(arr_Valid.T)
print("---------------------------------")

Array Iterating
1
2
3
4
5
6
7
8
9
---------------------------------
Array Reshaping
[[1 2 3 4 5 6 7 8 9]]
---------------------------------
Transpose
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
---------------------------------
